### ISSUE TITLE
How to add extra shared lib in apk.

### ISSUE THREAD

**Issue by songww** [rust-windowing/android-ndk-rs#64] opened 2020-08-19 14:17 UTC

**Comment by Daniihh** [comment] 2020-09-20 08:32
I don't think this is possible currently with `cargo-apk`, but there is Android developer documentation about the topic [here](https://developer.android.com/ndk/guides/prebuilts). I'd love to help implement this, but I'm not sure where to start..

**Comment by francesca64** [comment] 2020-10-28 00:13
@danii sorry for the delay! You have a cute profile pic.

I honestly don't know a lot about cargo-apk (since I use [my own tool](https://github.com/BrainiumLLC/cargo-mobile)), but it looks like we just need to add a config field for this, and then use that to generate an Android.mk as per the guide you linked.

We specify config fields here: https://github.com/rust-windowing/android-ndk-rs/blob/13914ef4c9ff39af289e26bb2f5d1ff12f91ca18/cargo-apk/src/manifest.rs#L7-L13 (usage shown [here](https://github.com/rust-windowing/android-ndk-rs/tree/13914ef4c9ff39af289e26bb2f5d1ff12f91ca18/cargo-apk#manifest))

We already generate an Android.mk here: https://github.com/rust-windowing/android-ndk-rs/blob/13914ef4c9ff39af289e26bb2f5d1ff12f91ca18/cargo-apk/src/apk.rs#L139-L142

It looks like we're currently only doing that when the `gdb` subcommand is used, so you'd have to move some things around.

**Comment by dvc94ch** [comment] 2021-01-13 15:25
Closing as a duplicate of #103 which explains how to do it until there are better docs.

**Closed by dvc94ch** 2021-01-13 15:25 UTC
Labels: type: documentation

**Comment by MarijnS95** [comment] 2021-01-13 16:00
In addition, note that #103 explains how to get solibs into the APK that Rust is already supposed to link against dynamically (eg. with `#[link]`). @songww please let us know know if you are instead looking for embedding dynamic libraries that are not linked against but rather opened through `dlopen` of some sort (or arbitrary files for that matter).

**Comment by songww** [comment] 2021-01-13 16:13
For example, liba.so is linked by rust, liba.so link to libb.so, How to add libb.so to apk? rust dose not link libb.so directly.
Sorry, my english is so poor.

**Comment by dvc94ch** [comment] 2021-01-13 16:48
It adds libs recursively by parsing the reader output, it should just work.

**Comment by songww** [comment] 2021-01-14 13:56
Well, thanks
